name = str(input('Enter student name: '))
gender = str(input('Enter student gender (male, female): '))
age = int(input('Enter student age: '))
group = str(input('Enter student group: '))
print('++++++++++++++++')
print(f"Student Name: {name}")
print(f"Student Gender: {gender}")
print(f"Student Age: {age}")
print(f"Student Group: {group}")
