name = str(input('Enter student name (max=10): '))
gender = str(input('Enter student gender (male, female): '))
age = int(input('Enter student age: '))
group = str(input('Enter student group(ST1, ST7) : '))
print('++++++++++++++++')
print(f"Student Name: {name}")
print(f"Student Gender: {gender}")
print(f"Student Age: {age}")
print(f"Student Group: {group}")
